# NumPy
- NumPy bilimsel hesaplamalar yapmak için pratik bir pakettir. Büyük ve çok boyutlu diziler ve matrisler için destek sunar.

In [1]:
import numpy as np

## Array Oluşturmak

In [5]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [6]:
type(a)

list

In [7]:
b = list(range(6, 11))
b

[6, 7, 8, 9, 10]

In [8]:
a + b   # liste toplama

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### np.array()

In [9]:
a1D = np.array(a)  # list, np.array tipine dönüştürüldü.

In [10]:
print(a1D)

[1 2 3 4 5]


In [11]:
type(a1D)

numpy.ndarray

In [12]:
b1D = np.array(b)

In [13]:
print(b1D)

[ 6  7  8  9 10]


In [14]:
a1D + b1D

array([ 7,  9, 11, 13, 15])

In [15]:
a1D - b1D

array([-5, -5, -5, -5, -5])

In [16]:
a1D * b1D

array([ 6, 14, 24, 36, 50])

In [17]:
a1D / b1D

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
a1D ** b1D

array([      1,     128,    6561,  262144, 9765625])

In [19]:
a, b

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [20]:
[a, b]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [21]:
a2D = np.array([a, b])

In [22]:
print(a2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
a2D * a2D

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

## 1D Array Oluşturma Fonksiyonları

### np.arange()

In [25]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.arange(10)   # stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(5, 10)  # start: 5 (dahil), stop: 10 (hariç)

array([5, 6, 7, 8, 9])

In [30]:
list(range(5, 10, 2))

[5, 7, 9]

In [31]:
np.arange(5, 10, 2)

array([5, 7, 9])

### np.linspace

In [33]:
# help(np.linspace)

In [34]:
np.linspace(0, 49)   # Docstringi görmek için Shift + Tab
                     # Default'u 50 tane sayı üretir. num parametresi ile bu sayı güncellenebilir.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [35]:
np.linspace(5, 50, num=10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [39]:
np.linspace(5, 50, num=21)

array([ 5.  ,  7.25,  9.5 , 11.75, 14.  , 16.25, 18.5 , 20.75, 23.  ,
       25.25, 27.5 , 29.75, 32.  , 34.25, 36.5 , 38.75, 41.  , 43.25,
       45.5 , 47.75, 50.  ])

## 2D Array Oluşturma Fonksiyonları

### np.eye

In [42]:
np.eye(5)     # Birim matris (Identity Matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(6, dtype=int)   # veri tipi integer

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### np.zeros

In [44]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [45]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
np.zeros((2, 3, 3))   # 3 boyutlu 0 lardan oluşan numpy array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
# 2 satır 3 sütun 1'lerden oluşan numpy array oluşturun
np.zeros(shape=(2,3), dtype=int) + 1

array([[1, 1, 1],
       [1, 1, 1]])

## Numpy Array'leri Çoğaltma, Birleştirme ve Değiştirme

In [51]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
b = a

In [54]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
b += 1

In [56]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [57]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
id(a)

2976226779632

In [59]:
id(b)

2976226779632

In [60]:
c = a.copy()

In [61]:
id(c)

2976226780400

In [62]:
c += 1

In [63]:
print(c)

[ 2  3  4  5  6  7  8  9 10 11]


In [64]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### np.vstack, np.hstack

In [65]:
a = np.array(range(1,5))
b = np.array(range(5,9))
c = np.array(range(9,13))
d = np.array(range(13,17))

In [66]:
print(a)
print(b)
print(c)
print(d)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [67]:
# Dikey olarak array birleştirme
np.vstack((a, b, c, d))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
# Yatay olarak array birleştirme
np.hstack((a, b, c, d))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### np.diag

In [69]:
np.diag((1, 2, 5, 7, 9))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

### np.ones

In [73]:
np.ones((5, 7), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

### np.block

## Rastgele (Random) NumPy Array'ler Oluşturmak

### rand

In [78]:
np.random.rand()      # [0, 1)

0.21791443103771613

In [79]:
np.random.rand(5)     # 1D Array

array([0.17772023, 0.19006137, 0.74461698, 0.45532692, 0.07687714])

In [80]:
np.random.rand(5, 4)  # 2D Array

array([[0.4924436 , 0.5374522 , 0.93998109, 0.65992458],
       [0.61028083, 0.28394755, 0.46198638, 0.111519  ],
       [0.39054665, 0.87807126, 0.91460417, 0.43271033],
       [0.00125411, 0.53798622, 0.3628234 , 0.44579061],
       [0.27667469, 0.65918469, 0.38593882, 0.10727697]])

In [82]:
# 3 satır 4 sütun, 0-10 arasında rastgele oluşan bir array oluşturun.
np.random.rand(3, 4) * 10

array([[3.24614268, 1.16475525, 4.41223037, 4.58268546],
       [2.57691623, 8.64208268, 0.47132012, 3.12710531],
       [4.20434582, 0.5629838 , 7.2284602 , 6.70743678]])

### randn

In [88]:
np.random.randn()    # standart normal dağılım, ort:0, std=1

-1.1200970920889861

In [89]:
np.random.randn(10)

array([ 0.50542672,  0.69369313,  0.77481742, -0.07777601, -0.80783144,
       -1.43416401, -0.34153953,  1.80509544,  1.46665842,  1.4572494 ])

In [90]:
big_arr = np.random.randn(100000)

In [91]:
type(big_arr)

numpy.ndarray

In [93]:
len(big_arr)

100000

In [94]:
big_arr.mean()   # büyük array'in ortalaması

-0.00391193465032912

In [95]:
big_arr.std()   # büyük array'in standart sapması

1.0032937752757334

In [96]:
big_arr.max()   # büyük array'in maksimumu

4.943349031543137

In [97]:
big_arr.min()   # büyük array'in minimumu

-4.739418410944709

In [98]:
big_arr.argmax() # maksimum değerin indeksi

96881

In [99]:
big_arr[96881]

4.943349031543137

In [100]:
big_arr.argmin() # minimum değerin indeksi

12232

In [101]:
big_arr[12232]

-4.739418410944709

### seed

In [105]:
np.random.seed(2222)    # Reproducability (Yeni Üretilebilirlik)
np.random.randn()

-0.9407914639148472

## Array'leri Yeniden Şekillendirmek (Reshaping Arrays)

In [108]:
arr = np.arange(20, 36)
print(arr)  # 16 elemanı olan tek boyutlu bir dizi

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [111]:
arr.shape

(16,)

In [113]:
arr = arr.reshape(4, 4)   # 16 elemanı olan 4x4'lük 2 boyutlu bir dizi
print(arr)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


In [114]:
arr.shape

(4, 4)

In [116]:
arr = arr.reshape(2, 8)
print(arr)

[[20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35]]


In [117]:
arr.shape

(2, 8)

In [121]:
arr = arr.reshape(16,1)
print(arr)

[[20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]]


In [122]:
arr.shape

(16, 1)

In [123]:
arr = arr.reshape(1,16)
print(arr)

[[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]


In [124]:
arr.shape

(1, 16)

In [125]:
arr = arr.reshape(2, 2, 4)
print(arr)

[[[20 21 22 23]
  [24 25 26 27]]

 [[28 29 30 31]
  [32 33 34 35]]]


In [126]:
arr = arr.reshape(2, 2, 2, 2)
print(arr)

[[[[20 21]
   [22 23]]

  [[24 25]
   [26 27]]]


 [[[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]]


## Indeksleme ve Dilimleme (Indexing and Slicing)

### Indexing

In [129]:
arr = np.arange(0, 35, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


In [130]:
arr[6]

12

In [131]:
len(arr)

18

In [132]:
arr = arr.reshape(3, 3, 2)
print(arr)

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]

 [[24 26]
  [28 30]
  [32 34]]]


In [133]:
arr[1]

array([[12, 14],
       [16, 18],
       [20, 22]])

In [134]:
arr[1][1]

array([16, 18])

In [136]:
arr[0][1][0]

4

In [137]:
arr[0, 1, 0]

4

In [138]:
arr

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]],

       [[24, 26],
        [28, 30],
        [32, 34]]])

In [139]:
arr[-1]

array([[24, 26],
       [28, 30],
       [32, 34]])

In [140]:
arr[-2 ,-2]

array([16, 18])

### Slicing

In [143]:
arr = np.arange(10, 35)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [144]:
arr[3:8]

array([13, 14, 15, 16, 17])

In [146]:
arr[-6:-2]

array([29, 30, 31, 32])

In [147]:
len(arr)

25

In [148]:
arr = arr.reshape(5, 5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [149]:
arr[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
arr[1:3][1:3]

array([[20, 21, 22, 23, 24]])

In [151]:
arr[1:3, 1:3]

array([[16, 17],
       [21, 22]])

In [153]:
arr[2:, 3:]

array([[23, 24],
       [28, 29],
       [33, 34]])

## Koşullu Filtreleme (Conditional Selection)

In [157]:
np.random.seed(51)
arr = np.random.randint(0, 100, size=50)
print(arr)

[57 96 73 69 16 21 94 52 37 37 60 94 28 84 36 35 27 28 42 10  6 25 33 77
 39 48 24 40 54 77 28 69 57 18 63 75 67 94 87  7 67 91 61 34 53 30 55 17
 67  8]


In [160]:
bool_arr = arr > 50   # boolean array
print(bool_arr)

[ True  True  True  True False False  True  True False False  True  True
 False  True False False False False False False False False False  True
 False False False False  True  True False  True  True False  True  True
  True  True  True False  True  True  True False  True False  True False
  True False]


In [161]:
arr[bool_arr]

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [162]:
arr[ arr > 50 ]   # 50'den büyük olanları filtrele

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [163]:
# Bir örnek daha
arr2 = np.array([1, 3, 4, 7, 8, 9])
bool_arr2 = np.array([False, False, True, False, True, False])

In [164]:
len(arr2)

6

In [165]:
len(bool_arr2)

6

In [166]:
arr2[bool_arr2]

array([4, 8])

In [167]:
# Bir örnek daha
np.random.seed(51)
arr3 = np.random.randint(125, 675, 100)
print(arr3)

[182 610 653 561 486 674 153 288 153 551 131 542 586 625 429 149 179 153
 316 200 377 475 596 344 415 562 283 180 654 242 566 266 212 194 366 177
 174 128 403 468 576 634 629 443 544 560 220 602 465 634 433 299 369 172
 209 506 603 484 358 297 565 369 486 549 476 137 580 292 481 562 166 241
 200 208 310 600 127 297 172 533 605 387 414 642 654 279 487 410 326 291
 625 539 386 451 282 396 306 624 495 585]


In [169]:
# 250'den büyük ve 400'den küçük sayıları filtreleyin
arr3[(arr3 > 250) & (arr3 < 400)]

array([288, 316, 377, 344, 283, 266, 366, 299, 369, 358, 297, 369, 292,
       310, 297, 387, 279, 326, 291, 386, 282, 396, 306])

#### 1 ile 100 (dahil) arasında rastgele seçilen 50 elemanı olan bir np.array oluşturun. Bu array'de 25'ten büyük sayıları filtreleyin ve bu sayıların toplamını söyleyin.  (seed=51)

In [170]:
np.random.seed(51)
arr = np.random.randint(1, 101, size=50)
print(arr)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [171]:
arr[arr > 25]

array([58, 97, 74, 70, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28, 29, 43,
       26, 34, 78, 40, 49, 41, 55, 78, 29, 70, 58, 64, 76, 68, 95, 88, 68,
       92, 62, 35, 54, 31, 56, 68])

In [172]:
sum(arr[arr > 25])  # python builtin sum function

2381

In [173]:
arr[arr > 25].sum() # numpy array sum methodu

2381

In [174]:
arr[arr > 25].mean()

58.073170731707314

In [175]:
arr[arr > 25].std()

21.76413501321129

In [176]:
arr[arr > 25].min()

26

In [177]:
arr[arr > 25].max()

97

In [178]:
arr[arr > 25].var()

473.6775728732897

## NumPy Operations

### Arithmetic Operations

In [179]:
a = np.array([4, 5, 6])
b = np.array([1, 2, 3])

In [180]:
a + b

array([5, 7, 9])

In [181]:
a - b

array([3, 3, 3])

In [182]:
a * b

array([ 4, 10, 18])

In [183]:
a / b

array([4. , 2.5, 2. ])

In [184]:
a ** b

array([  4,  25, 216])

In [185]:
a // b

array([4, 2, 2])

In [186]:
a % b

array([0, 1, 0])

In [187]:
np.add(a, b)   # a + b

array([5, 7, 9])

In [188]:
np.subtract(a, b)  # a - b

array([3, 3, 3])

In [189]:
np.multiply(a, b)  # a * b

array([ 4, 10, 18])

In [190]:
np.divide(a, b)    # a / b

array([4. , 2.5, 2. ])

In [191]:
np.power(a, b)    # a ** b

array([  4,  25, 216])

In [192]:
np.inf   # sonsuz

inf

In [193]:
np.pi    # pi sayısı

3.141592653589793

### Statistical Operations

In [194]:
arr

array([58, 97, 74, 70, 17, 22, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28,
       29, 43, 11,  7, 26, 34, 78, 40, 49, 25, 41, 55, 78, 29, 70, 58, 19,
       64, 76, 68, 95, 88,  8, 68, 92, 62, 35, 54, 31, 56, 18, 68,  9])

In [195]:
# Array'i sıralama
arr.sort()

In [196]:
arr

array([ 7,  8,  9, 11, 17, 18, 19, 22, 25, 26, 28, 29, 29, 29, 31, 34, 35,
       36, 37, 38, 38, 40, 41, 43, 49, 53, 54, 55, 56, 58, 58, 61, 62, 64,
       68, 68, 68, 70, 70, 74, 76, 78, 78, 85, 88, 92, 95, 95, 95, 97])

#### mean

In [197]:
np.mean(arr)

50.34

In [198]:
arr.mean()

50.34

#### median

In [199]:
np.median(arr)

51.0

#### std var

In [201]:
np.std(arr)

25.839976780175327

In [203]:
arr.std()

25.839976780175327

In [204]:
np.var(arr)

667.7044000000001

In [205]:
arr.var()

667.7044000000001

#### sum

In [206]:
np.sum(arr)

2517

In [207]:
arr.sum()

2517

#### min max

In [208]:
np.min(arr)

7

In [209]:
arr.min()

7

In [210]:
np.max(arr)

97

In [211]:
arr.max()

97

#### percentile

In [213]:
print(arr)

[ 7  8  9 11 17 18 19 22 25 26 28 29 29 29 31 34 35 36 37 38 38 40 41 43
 49 53 54 55 56 58 58 61 62 64 68 68 68 70 70 74 76 78 78 85 88 92 95 95
 95 97]


In [212]:
np.percentile(arr, 50)  # 50th percentile, Q2, median

51.0

In [215]:
np.percentile(arr, 25)  # 25th percentile, Q1

29.0

In [216]:
np.percentile(arr, 75)  # 75th percentile, Q3

69.5

## Correlation

In [217]:
height = np.array([177, 192, 178, 158, 165, 168, 164, 161])
weight = np.array([85, 95, 74, 65, 60, 52, 52, 63])

In [218]:
np.corrcoef(height, weight)

array([[1.        , 0.83138299],
       [0.83138299, 1.        ]])